export const USER_ROLES = {
  STUDENT: 'student',
  ADMINISTRATOR: 'administrator',
  ELECTORAL_COMMITTEE: 'electoral_committee',
  CANDIDATE: 'candidate',
} as const;

export type UserRole = typeof USER_ROLES[keyof typeof USER_ROLES];

export const ELECTION_STATUSES = {
  DRAFT: 'draft',
  SCHEDULED: 'scheduled',
  CAMPAIGN: 'campaign',
  VOTING_OPEN: 'voting_open',
  PAUSED: 'paused',
  VOTING_CLOSED: 'voting_closed',
  RESULTS_PUBLISHED: 'results_published',
} as const;

export type ElectionStatus = typeof ELECTION_STATUSES[keyof typeof ELECTION_STATUSES];

export const ALLOWED_DOMAINS = ['@uandresbello.edu', '@unab.cl'];

export const STATUS_TRANSITIONS = {
  [ELECTION_STATUSES.DRAFT]: [ELECTION_STATUSES.SCHEDULED, ELECTION_STATUSES.VOTING_OPEN],
  [ELECTION_STATUSES.SCHEDULED]: [ELECTION_STATUSES.CAMPAIGN, ELECTION_STATUSES.VOTING_OPEN, ELECTION_STATUSES.DRAFT],
  [ELECTION_STATUSES.CAMPAIGN]: [ELECTION_STATUSES.VOTING_OPEN, ELECTION_STATUSES.SCHEDULED],
  [ELECTION_STATUSES.VOTING_OPEN]: [ELECTION_STATUSES.PAUSED, ELECTION_STATUSES.VOTING_CLOSED],
  [ELECTION_STATUSES.PAUSED]: [ELECTION_STATUSES.VOTING_OPEN, ELECTION_STATUSES.VOTING_CLOSED],
  [ELECTION_STATUSES.VOTING_CLOSED]: [ELECTION_STATUSES.RESULTS_PUBLISHED],
  [ELECTION_STATUSES.RESULTS_PUBLISHED]: [],
};

export const STATUS_COLORS = {
  [ELECTION_STATUSES.DRAFT]: 'text-gray-400 bg-gray-800',
  [ELECTION_STATUSES.SCHEDULED]: 'text-blue-400 bg-blue-900/20',
  [ELECTION_STATUSES.CAMPAIGN]: 'text-purple-400 bg-purple-900/20',
  [ELECTION_STATUSES.VOTING_OPEN]: 'text-green-400 bg-green-900/20',
  [ELECTION_STATUSES.PAUSED]: 'text-yellow-400 bg-yellow-900/20',
  [ELECTION_STATUSES.VOTING_CLOSED]: 'text-orange-400 bg-orange-900/20',
  [ELECTION_STATUSES.RESULTS_PUBLISHED]: 'text-emerald-400 bg-emerald-900/20',
};